"""updated  column header

Revision ID: 4c03288ab434
Revises: 1a73e429f0df
Create Date: 2021-04-13 22:56:32.305570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c03288ab434'
down_revision = '1a73e429f0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.drop_column('user', 'date_create')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_create', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
